version: 0.2

phases:
  pre_build:
    commands:
      - echo Preparing Dockerfile-based Elastic Beanstalk deployment

  build:
    commands:
      - echo Moving backend Dockerfile and source to root
      - mkdir -p zoning-backend
      - cp backend/Dockerfile zoning-backend/
      - cp -r backend/src zoning-backend/
      - cp backend/pom.xml zoning-backend/

artifacts:
  base-directory: zoning-backend
  files:
    - '**/*'