services:
  - type: web
    name: zoning-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
